### ISSUE TITLE
Attempt to invoke virtual method 'float android.text.Layout.getLineLeft(int)' on a null object reference

### ISSUE THREAD

**Issue by janvalji** [hanks-zyh/HTextView#115]
The application is constantly crashing. it sometimes improves when it starts with a delay, but when I press the home button (at the time of loading) it gives an error. you have to help .. everyone is waiting for your help on this issue
@hanks-zyh 

'float android.text.Layout.getLineLeft(int)'

```
`java.lang.NullPointerException: 
  at com.hanks.htextview.evaporate.EvaporateText$3.run (EvaporateText.java:2)
  at android.os.Handler.handleCallback (Handler.java:914)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:225)
  at android.app.ActivityThread.main (ActivityThread.java:7564)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)`
```

**Comment by bumibest** [comment]
Same here
```
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.text.Layout.getLineLeft(int)' on a null object reference
        at com.hanks.htextview.scale.ScaleText.drawFrame(ScaleText.java:98)
        at com.hanks.htextview.base.HText.onDraw(HText.java:114)
        at com.hanks.htextview.scale.ScaleTextView.onDraw(ScaleTextView.java:44)``
```
