### ISSUE TITLE
hello,gay,my app show OutOfMemoryError in the HTextView.animateText

### ISSUE THREAD

**Issue by huiming666** [hanks-zyh/HTextView#18]
version: 
compile 'hanks.xyz:htextview-library:0.1.3'

exception stack:

java.lang.OutOfMemoryError
                                                                                at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
                                                                                at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
                                                                                at android.graphics.Bitmap.createBitmap(Bitmap.java:636)
                                                                                at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:516)
                                                                                at com.hanks.htextview.animatetext.AnvilText.animateStart(AnvilText.java:67)
                                                                                at com.hanks.htextview.animatetext.HText.animateText(HText.java:74)
                                                                                at com.hanks.htextview.HTextView.animateText(HTextView.java:97)
                                                                                at com.antzb.fragment.AntMapFragment.showHotActive(AntMapFragment.java:192)

**Comment by hanks-zyh** [comment]
@huiming666  Sorry, that is a bug,   I don't suggest use it in product environment

**Comment by hanks-zyh** [comment]
fixed: https://github.com/hanks-zyh/HTextView/commit/15ccfa93388e935e3f24ffe3cbadc7330427e6b6
