### ISSUE TITLE
It doesn't works except when I set htext:animateType="typer".

### ISSUE THREAD

**Issue by YuFong** [hanks-zyh/HTextView#33]

**Comment by hanks-zyh** [comment]
@YuFong  I test all animateType work well , could you please provide more info?

**Comment by YuFong** [comment]
When I set animateType to "anvil",it can not display normally.And then I set animateType  to "evaporate",it works at the first I launched my app,but when I quit my app and restart it,then "evaporate" can not work either.Other type seems to have the same pro.

**Comment by YuFong** [comment]
When I set type to "rainbow",I got this Exception which cause my app crash.
```java
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: yu.unsplash, PID: 31422
                  Theme: themes:{default=overlay:jahirfiquitiva.themes.meliornui, fontPkg:jahirfiquitiva.themes.meliornui, com.android.systemui=overlay:jahirfiquitiva.themes.meliornui, com.android.systemui.navbar=overlay:jahirfiquitiva.themes.meliornui}
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.LinearGradient.setLocalMatrix(android.graphics.Matrix)' on a null object reference
                      at com.hanks.htextview.animatetext.RainBowText.drawFrame(RainBowText.java:49)
                      at com.hanks.htextview.animatetext.HText.onDraw(HText.java:80)
                      at com.hanks.htextview.HTextView.onDraw(HTextView.java:112)
                      at android.view.View.draw(View.java:16187)
                      at android.view.View.updateDisplayListIfDirty(View.java:15184)
                      at android.view.View.draw(View.java:15957)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.draw(View.java:16190)
                      at android.view.View.updateDisplayListIfDirty(View.java:15184)
                      at android.view.View.draw(View.java:15957)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15179)
                      at android.view.View.draw(View.java:15957)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15179)
                      at android.view.View.draw(View.java:15957)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15179)
                      at android.view.View.draw(View.java:15957)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.updateDisplayListIfDirty(View.java:15179)
                      at android.view.View.draw(View.java:15957)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                      at android.view.View.draw(View.java:16190)
                      at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2946)
                      at android.view.View.updateDisplayListIfDirty(View.java:15184)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2623)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2442)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2075)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                      at android.view.Choreographer.doFrame(Choreographer.java:606)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5461)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by hanks-zyh** [comment]
@YuFong  https://github.com/hanks-zyh/HTextView/issues/29 lasted commit has solved this 'rainBow' type
