### ISSUE TITLE
ScaleText crash

### ISSUE THREAD

**Issue by Kolyall** [hanks-zyh/HTextView#56]
```
ScaleTextView mToolbarTitle = (ScaleTextView) findViewById(R.id.toolbar_title);
mToolbarTitle.animateText(title);
```

```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.text.Layout.getLineLeft(int)' on a null object reference
                                                                          at com.hanks.htextview.scale.ScaleText.animateText(ScaleText.java:49)
                                                                          at com.hanks.htextview.scale.ScaleTextView.animateText(ScaleTextView.java:48)
```

**Comment by RJFares** [comment]
+1

**Comment by drecrumbs** [comment]
+1

**Comment by cbriseno** [comment]
Same here

**Comment by MrshaoGx** [comment]
Seems like mHTextView doesn't initialized...but how ? i can't init it in xml file...

**Comment by MrshaoGx** [comment]
I got it.compare with demo and i found that trick is mHTextView.getLayout() is null, mean this view not measure yet,so what we need to do is to delay few seconds. demo was manually control,so i added post code....

**Comment by chenyusheng** [comment]
+1
i got the same crash

**Comment by chenyusheng** [comment]
@MrshaoGx and it work now?

**Comment by MrshaoGx** [comment]
能用了啊，创建的时候控件给post事件里写就好了，或者手动控制。。

**Comment by chenyusheng** [comment]
@MrshaoGx 这就有点尴尬了。。。作者这bug也不修修。。。

**Comment by hanks-zyh** [comment]
fixed it
