### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by Jublikon** [hanks-zyh/HTextView#7]
I have placed the animated view inside of a fragment that is hold by a ViewPager.
When I make the fragment visible for the first time everything is alright. 
But when the fragment gets reloaded I get the following issue: 

 FATAL EXCEPTION: main
                                                                  Process: com.ads.adstimer, PID: 14680
                                                                  java.lang.OutOfMemoryError: Failed to allocate a 2007612 byte allocation with 1750816 free bytes and 1709KB until OOM
                                                                      at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                      at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:739)
                                                                      at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:615)
                                                                      at com.hanks.htextview.animatetext.AnvilText.animateStart(AnvilText.java:67)
                                                                      at com.hanks.htextview.animatetext.HText.animateText(HText.java:74)
                                                                      at com.hanks.htextview.HTextView.animateText(HTextView.java:97)
                                                                      at com.ads.adstimer.fragment.Registration.Slides.FragmentScanCode.onCreateView(FragmentScanCode.java:37)
                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                      at android.support.v4.app.FragmentManagerImpl.attachFragment(FragmentManager.java:1426)
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:728)
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                      at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                      at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                                      at android.support.v4.view.ViewPager$3.run(ViewPager.java:251)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

I hope, you can solve it. 
I really like that library, good job!

**Comment by hanks-zyh** [comment]
@EnduroXPro  Thank you for your feedback ， I'm trying some way to fix OOM  . if you can solve it , welcome to commit  pull request

**Comment by xu6148152** [comment]
I don't think that 
```System.gc() 
```
can always fix oom.

It's document
```
/**
     * Indicates to the VM that it would be a good time to run the
     * garbage collector. Note that this is a hint only. There is no guarantee
     * that the garbage collector will actually be run.
     */
```

**Comment by hanks-zyh** [comment]
@xu6148152  yes，`System.gc() ` can't solve OOM problem, it should change the implement of the library if we want to sovle it fundamentally

**Comment by wangmuge** [comment]
会发生OOM

**Comment by mattvb91** [comment]
Same issue here

**Comment by mohitpant9** [comment]
android:largeHeap="true"
in manifest file inside application Tag

**Comment by hanks-zyh** [comment]
AnvilText had been deleted
