### ISSUE TITLE
EvaporateText getLineLeft NPE

### ISSUE THREAD

**Issue by Anzhi-Meiying** [hanks-zyh/HTextView#96]
`    java.lang.NullPointerException: Attempt to invoke virtual method 'float android.text.Layout.getLineLeft(int)' on a null object reference
        at com.hanks.htextview.evaporate.EvaporateText$3.run(EvaporateText.java:65)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)`

这个 BUG 什么时候才能修复呀，如果不能修复能不能加个判断，如果为空就不做动画了

**Comment by pcegarra** [comment]
+1 this library isnt working

**Comment by Anzhi-Meiying** [comment]
@hanks-zyh 大佬请问何时修复一下下

**Comment by sebinpaul** [comment]
I'm too facing this issue. Can anybody suggest me some workaround for this?

**Comment by gordonfreemanix** [comment]
ups
